# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
modules:
  - type: dnf
    install:
      packages:
        # - langpacks-en
        # - nss-tools
        - socat
        - gnome-shell-extension-system-monitor-applet
        - netcat
        # - fastfetch
        # - clinfo
        - hwinfo
        - gparted
        - mc
        - onedrive
        - gh
        - duc
        - age
        - gopass
        - opentofu
        - cloud-utils-cloud-localds
        - pipx
        - awscli2
        - chezmoi
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        # Need Node.js for some tools like Claude Code
        - nodejs
